//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FromSoftwareStorage.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public string Name { get; set; }
        public string Directory { get; set; }
        public string DefaultFileName { get; set; }
        public string FileSearchPattern { get; set; }
        public string DefaultDirectory { get; set; }
        public string RootDirectory { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public bool ReadOnly { get; set; }
        public Nullable<int> FolderId { get; set; }
    
        public virtual Folder Folder { get; set; }
        public virtual Image Image { get; set; }
    }
}
